### ISSUE TITLE
question: release reflected name?

### ISSUE THREAD

**Issue by avkonst** [VladasZ/reflected#1]
Hi! I checked your library and understand it was an experiment and not actively maintained. I wonder if you would be ok with releasing the `reflected` name in the cargo registry for another toolkit. We are about to opensource a tool which replaces openapi based API definitions. It is rust-code first API over HTTP schema definition, which uses derive macro to inspect relevant Rust code and produce the schema. The schema is used to generates type safe compatible clients in Typescript and Rust (other languages will be added by us or by community). We are using previous generation of it in production, and now moving to to-be-soon opensource based. We think reflected would be ideal name for this project. What do you think?

**Comment by VladasZ** [comment]
Hi. I wouldn't say that is it not actively maintained. Yes it lacks documentation and I started this as an experiment but so far this experiment was somewhat successful and I use this crate in several of my projects. You can see recent downloads on: https://crates.io/crates/reflected . And I have some plans to improve this crate in the future. This crate purpose is literally reflection and I think `reflected` is a good name for it. So I would like to keep that name. Unless you can come up with a better name for a crate which generates information about structure fields and types and I will like it more than current name.

**Comment by VladasZ** [comment]
So I'm closing the issue if you don't have anything else to add.
